#!/bin/bash
# luma3ds

# Define directories
dir_luma3ds=~/Documents/3ds/luma3ds
dir_src=~/src
dir_out=$dir_src/out
dir_build=$dir_src/build
dir_luma=$dir_out/luma
dir_sys=$dir_luma/sys
dir_payloads=$dir_luma/payloads
dir_3ds_injector_files=~/Documents/3ds/3ds_injector_files
dir_cia=$dir_luma/cia
dir_cia_apps=$dir_cia/apps
dir_cia_games=$dir_cia/games
dir_cia_updates=$dir_cia/updates
dir_tmp=$dir_luma/tmp

# Dependencies
dir_a9lh_files=~/Documents/3ds/a9lh_files
dir_decrypt9wip_files=~/Documents/3ds/decrypt9wip_files
dir_cia_files=~/Documents/3ds/cia_files
dir_misc_files=~/Documents/3ds/misc_files
dir_filer=~/Documents/3ds/filer

# Luma3DS Menu
echo "**** Luma3DS Menu ****";
echo "[1] Build CFW";
echo "[2] Update repository";
echo -n "Select your choice: ";
read choice;

case $choice in
	1)
	# Clean src directory
	rm -rf $dir_build $dir_out $dir_src/smdc*;
	mkdir -vp $dir_build $dir_out $dir_luma; $dir_sys;
	mkdir -vp $dir_cia $dir_cia_apps $dir_cia_games $dir_cia_updates $dir_tmp; 
	cp -rR $dir_luma3ds/* $dir_build/;
	
	# Luma3DS
	cd $dir_build/Luma3DS;
	make clean;
	sed 's|filepath ?=|filepath ?= luma/|g' $dir_build/Luma3DS/CakeBrah/Makefile;
	sed 's|filepath ?=|filepath ?= luma/|g' $dir_build/Luma3DS/CakeHax/Makefile;
	cd $dir_build/Luma3DS;
	make;
	mv -v $dir_build/Luma3DS/out/luma/* $dir_out/luma/;
	mv -v $dir_build/Luma3DS/out/arm9loaderhax.bin $dir_out/luma/payloads/def_luma3ds.bin;
	mv -v $dir_build/Luma3DS/out/3ds/Luma3DS/Luma3DS.3dsx $dir_out/luma/;
	mv -v $dir_build/Luma3DS/out/3ds/Luma3DS/Luma3DS.smdh $dir_out/luma/;
	echo "Done!";
	
	# Arm9loaderhax n3ds
  	cd $dir_build/arm9loaderhax;
  	make clean;
  	cd $dir_build/arm9loaderhax/payload_stage2/source;
  	sed -i -e 's|"arm9loaderhax.bin"|"/luma/boot.bin"|g' main.c;
  	cd $dir_build/arm9loaderhax/payload_installer/installer/source;
  	sed -i -e 's|"sdmc:/arm9loaderhax.pack"|"sdmc:/luma/sys/arm9loaderhax-n3ds/arm9loaderhax.pack"|g' main.c;
  	cp -v $dir_a9lh_files/new3ds10.firm $dir_build/arm9loaderhax/data_input;
  	cp -v $dir_a9lh_files/new3ds90.firm $dir_build/arm9loaderhax/data_input;
  	cp -v $dir_a9lh_files/secret_sector.bin $dir_build/arm9loaderhax/data_input;
  	cp -v $dir_a9lh_files/otp.bin-n3ds $dir_build/arm9loaderhax/data_input/otp.bin;
  	cd $dir_build/arm9loaderhax/;
  	make;
  	mv -v $dir_build/arm9loaderhax/data_output $dir_sys/arm9loaderhax-n3ds;
  	cp -v $dir_sys/arm9loaderhax-n3ds/arm9loaderhax.bin $dir_luma/payloads/x_arm9loaderhax.bin;
  	rm -rf $dir_build/arm9loaderhax; cp -rR $dir_luma3ds/arm9loaderhax $dir_build/;
  	echo "Done!";
  
  	# Decrypt9WIP
	cd $dir_build/Decrypt9WIP;
	make clean;
	cd $dir_build/Decrypt9WIP/source/decryptor;
	sed -i -e 's|"aeskeydb.bin"|"/luma/sys/aeskeydb.bin"|g' keys.c;
	cd $dir_build/Decrypt9WIP;
	make bootstrap;
	mv -v $dir_build/Decrypt9WIP/output/Decrypt9WIP.bin $dir_bin/up_decrypt9wip.bin;
	cp -v $dir_decrypt9wip_files/aeskeydb.bin $dir_bin/;
	echo "Done!";

	# EmuNAND9
	cd $dir_build/EmuNAND9;
	make clean;
	cd $dir_build/EmuNAND9/source;
	cd $dir_build/EmuNAND9;
	make bootstrap;
	mv -v $dir_build/EmuNAND9/output/EmuNAND9.bin $dir_bin/right_emunand9.bin;
	echo "Done!";

	# Godmode9
	cd $dir_build/GodMode9;
	make clean;
	make bootstrap;
	mv -v $dir_build/GodMode9/output/GodMode9.bin $dir_bin/left_godmode9.bin;
	echo "Done!";

	# Uncart
	cd $dir_build/uncart;
	make clean;
	make;
	mv -v $dir_build/uncart/arm9loaderhax.bin $dir_bin/down_uncart.bin;
	echo "Done!";
  	
  	# FBI
	cd $dir_build/FBI;
	make clean;
	make;
	cp -v $dir_build/FBI/output/FBI.cia $dir_cia_apps/fbi-$(date +%m-%d-%Y).cia;
	echo "Done!";

	# ftpd
	cd $dir_build/ftpd;
	make clean;
	make;
	cp -v $dir_build/ftpd/output/ftpd.cia $dir_cia_apps/ftpd-$(date +%m-%d-%Y).cia;
	echo "Done!";
	
	# Copy depencencies
	cp -rR $dir_3ds_injector_files/locales $dir_sys/;
	cp -v $dir_cia_files/apps/*.cia $dir_cia/apps/;
	cp -v $dir_misc_files/boot.3dsx $dir_out;
	cp -rR $dir_filer $dir_out/;
	mkdir -vp $dir_tmp/db; touch $dir_tmp/db/title.db $dir_tmp/db/import.db;
	cp -rR $dir_decrypt9wip_files/n3ds $dir_tmp/hs-n3ds; cp -rR $dir_decrypt9wip_files/o3ds $dir_tmp/hs-o3ds;

	# Cleanup
	cd ~/src;
	rm -rf $dir_build;
	mv -v $dir_out sdmc_luma3ds-$(date +%m-%d-%Y);
	echo "";
	echo "Build finished!";
	;;
	
  	2)
    	mkdir -vp $dir_luma3ds; rm -rf $dir_luma3ds; mkdir -vp $dir_luma3ds;
    	cd $dir_luma3ds;
    	echo "Fetching Homebrew...";
    	git clone --recursive https://github.com/AuroraWright/Luma3DS.git;
    	git clone --recursive https://github.com/delebile/arm9loaderhax.git
    	git clone --recursive https://github.com/d0k3/Decrypt9WIP.git;
    	git clone --recursive https://github.com/d0k3/EmuNAND9.git;
    	git clone --recursive https://github.com/d0k3/GodMode9.git;
    	git clone --recursive https://github.com/Steveice10/FBI.git;
    	git clone --recursive https://github.com/3xkrazy/ftpd.git;
    	echo "";
    	echo "Repository updated!";
    	
    	exit 0;
    	;;
    
  	*)
    	echo "";
    	echo "You selected an invalid choice!";
    	
    	exit 1;
    	;;
esac
