#!/bin/bash
# luma3ds

# Define directories
dir_luma3ds=~/Documents/3ds/luma3ds
dir_src=~/src
dir_out=$dir_src/out
dir_build=$dir_src/build
dir_luma=$dir_out/luma
dir_sys=$dir_luma/sys
dir_payloads=$dir_luma/payloads
dir_locales=~/Documents/3ds/locales
dir_cia=$dir_luma/cia
dir_cia_apps=$dir_cia/apps
dir_cia_games=$dir_cia/games
dir_cia_updates=$dir_cia/updates
dir_tmp=$dir_sys/tmp

# Dependencies
dir_a9lh_n3ds=~/Documents/3ds/a9lh_files/n3ds
dir_decrypt9wip_files=~/Documents/3ds/decrypt9wip_files
dir_cia_files=~/Documents/3ds/cia_files
dir_misc_files=~/Documents/3ds/misc_files
dir_filer=~/Documents/3ds/filer

# Luma3DS Menu
echo "";
echo "**** Luma3DS Menu ****";
echo "[1] Build CFW";
echo "[2] Update repository";
echo -n "Select your choice: ";
read choice;

case $choice in
	1)
	# Clean src directory
	rm -rf $dir_build $dir_out $dir_src/sdmc*;
	mkdir -vp $dir_build $dir_out $dir_luma $dir_sys;
	mkdir -vp $dir_cia $dir_cia_apps $dir_cia_games $dir_cia_updates $dir_tmp; 
	cp -rR $dir_luma3ds/* $dir_build/;
	
	# Luma3DS
	cd $dir_build/Luma3DS;
	make clean;
	sed -i -e 's|filepath ?=|filepath ?= luma/|g' $dir_build/Luma3DS/CakeBrah/Makefile;
	sed -i -e 's|filepath ?=|filepath ?= luma/|g' $dir_build/Luma3DS/CakeHax/Makefile;
	cd $dir_build/Luma3DS;
	make;
	mv -v $dir_build/Luma3DS/out/luma/* $dir_out/luma/;
	cp -v $dir_build/Luma3DS/out/arm9loaderhax.bin $dir_payloads/boot.bin;
	
	# Arm9loaderhax
	cd $dir_build/arm9loaderhax;
	make clean;
	cd $dir_build/arm9loaderhax/payload_stage2/source;
	sed -i -e 's|"arm9loaderhax.bin"|"/luma/payloads/boot.bin"|g' main.c
	cd $dir_build/arm9loaderhax;
	make;
	
	# SafeA9LHInstaller
	cd $dir_build/SafeA9LHInstaller;
	make clean;
	cd $dir_build/SafeA9LHInstaller/source/;
	sed -i -e 's|"a9lh/otp.bin"|"luma/sys/SafeA9LHInstaller/otp.bin"|g' installer.c
	sed -i -e 's|"a9lh/secret_sector.bin"|"luma/sys/SafeA9LHInstaller/secret_sector.bin"|g' installer.c
	sed -i -e 's|"a9lh/firm0.bin"|"luma/sys/SafeA9LHInstaller/firm0.bin"|g' installer.c
	sed -i -e 's|"a9lh/firm1.bin"|"luma/sys/SafeA9LHInstaller/firm1.bin"|g' installer.c
	sed -i -e 's|"a9lh/payload_stage1.bin"|"luma/sys/SafeA9LHInstaller/payload_stage1.bin"|g' installer.c
	sed -i -e 's|"a9lh/payload_stage2.bin"|"luma/sys/SafeA9LHInstaller/payload_stage2.bin"|g' installer.c
	cd $dir_build/SafeA9LHInstaller/CakeBrah/;
	sed -i -e 's|filepath ?=|filepath ?= luma/sys/SafeA9LHInstaller/|g' Makefile;
	cd $dir_build/SafeA9LHInstaller/CakeHax/;
	sed -i -e 's|filepath ?=|filepath ?= luma/sys/SafeA9LHInstaller/|g' Makefile;
	cd $dir_build/SafeA9LHInstaller;
	make;
	mv -v $dir_build/SafeA9LHInstaller/out/arm9loaderhax.bin $dir_payloads/x_safea9lhinstaller.bin;
	mkdir -v $dir_sys/SafeA9LHInstaller;
	mv -v $dir_build/SafeA9LHInstaller/out/3ds/* $dir_sys/SafeA9LHInstaller/;
	mv -v $dir_build/SafeA9LHInstaller/out/SafeA9LHInstaller.dat $dir_sys/SafeA9LHInstaller/;
	mv -v $dir_build/arm9loaderhax/out/* $dir_sys/SafeA9LHInstaller/;
	cp -v $dir_a9lh_n3ds/* $dir_sys/SafeA9LHInstaller/;
	
  	# Decrypt9WIP
	cd $dir_build/Decrypt9WIP;
	make clean;
	cd $dir_build/Decrypt9WIP/source/decryptor;
	sed -i -e 's|"aeskeydb.bin"|"/luma/sys/aeskeydb.bin"|g' keys.c;
	cd $dir_build/Decrypt9WIP;
	make;
	mv -v $dir_build/Decrypt9WIP/output/Decrypt9WIP.bin $dir_payloads/up_decrypt9wip.bin;
	cp -v $dir_decrypt9wip_files/aeskeydb.bin $dir_sys/;

	# EmuNAND9
	cd $dir_build/EmuNAND9;
	make clean;
	cd $dir_build/EmuNAND9/source;
	cd $dir_build/EmuNAND9;
	make;
	mv -v $dir_build/EmuNAND9/output/EmuNAND9.bin $dir_payloads/right_emunand9.bin;

	# Godmode9
	cd $dir_build/GodMode9;
	make clean;
	make;
	mv -v $dir_build/GodMode9/output/GodMode9.bin $dir_payloads/left_godmode9.bin;

	# Uncart
	cd $dir_build/uncart;
	make clean;
	make;
	mv -v $dir_build/uncart/arm9loaderhax.bin $dir_payloads/down_uncart.bin;
  	
  	# FBI
	cd $dir_build/FBI;
	make clean;
	make;
	cp -v $dir_build/FBI/output/FBI.cia $dir_cia_apps/fbi-$(date +%m-%d-%Y).cia;

	# ftpd
	cd $dir_build/ftpd;
	make clean;
	make;
	cp -v $dir_build/ftpd/output/ftpd.cia $dir_cia_apps/ftpd-$(date +%m-%d-%Y).cia;
	
	# Copy depencencies
	cp -rR $dir_locales $dir_luma/;
	cp -v $dir_cia_files/apps/*.cia $dir_cia/apps/;
	cp -v $dir_misc_files/boot.3dsx $dir_out;
	cp -rR $dir_filer $dir_out/;
	mkdir -vp $dir_tmp/db; touch $dir_tmp/db/title.db $dir_tmp/db/import.db;
	cp -rR $dir_decrypt9wip_files/n3ds $dir_tmp/hs-n3ds; cp -rR $dir_decrypt9wip_files/o3ds $dir_tmp/hs-o3ds;

	# Cleanup
	cd ~/src;
	#rm -rf $dir_build;
	mv -v $dir_out sdmc_luma3ds-$(date +%m-%d-%Y);
	echo "";
	echo "Build finished!";
	;;
	
	2)
    	mkdir -vp $dir_luma3ds; rm -rf $dir_luma3ds; mkdir -vp $dir_luma3ds;
    	cd $dir_luma3ds;
    	echo "Fetching Homebrew...";
    	git clone --recursive https://github.com/AuroraWright/Luma3DS.git;
    	git clone --recursive -b noscreeninit https://github.com/AuroraWright/arm9loaderhax.git
    	git clone --recursive https://github.com/AuroraWright/SafeA9LHInstaller.git
    	git clone --recursive https://github.com/d0k3/Decrypt9WIP.git;
    	git clone --recursive https://github.com/d0k3/EmuNAND9.git;
    	git clone --recursive https://github.com/d0k3/GodMode9.git;
    	git clone --recursive https://github.com/AuroraWright/uncart.git
    	git clone --recursive https://github.com/Steveice10/FBI.git;
    	git clone --recursive https://github.com/3xkrazy/ftpd.git;
    	echo "";
    	echo "Repository updated!";
    	
    	exit 0;
    	;;
	
  	*)
    	echo "";
    	echo "You selected an invalid choice!";
    	
    	exit 1;
    	;;
esac
