#!/bin/bash

# CakesFW NATIVE_FIRM urls
n3ds_firm=http://nus.cdn.c.shop.nintendowifi.net/ccs/download/0004013820000002/0000001B
n3ds_cetk=http://nus.cdn.c.shop.nintendowifi.net/ccs/download/0004013820000002/cetk
o3ds_firm=http://nus.cdn.c.shop.nintendowifi.net/ccs/download/0004013800000002/00000049
o3ds_cetk=http://nus.cdn.c.shop.nintendowifi.net/ccs/download/0004013800000002/cetk

# Dependencies directory
dep=~/3DS/files

# BootNTR url
ntr=https://github.com/44670/BootNTR/releases/download/3.2/NTR.3.2.zip

# Directories
dir_build=~/src/build
dir_out=~/src/out
dir_3ds=~/src/out/3ds
dir_cia=~/src/out/cia
dir_a9lh=~/src/out/a9lh_payloads

# Make directories
mkdir -vp $dir_build
mkdir -vp $dir_out
mkdir -vp $dir_3ds
mkdir -vp $dir_cia/apps
mkdir -vp $dir_cia/games
mkdir -vp $dir_cia/updates
mkdir -vp $dir_a9lh

# Fetch the homebrew from github
echo "Fetching homebrew...";
cd $dir_build;
git clone --recursive https://github.com/delebile/Brahma2.git
git clone --recursive https://github.com/d0k3/uncart.git
git clone --recursive https://github.com/d0k3/EmuNAND9.git
git clone --recursive https://github.com/d0k3/Decrypt9WIP.git
git clone --recursive https://github.com/d0k3/MiniPasta.git
git clone --recursive https://github.com/mid-kid/CakesForeveryWan.git
git clone --recursive https://github.com/Reisyukaku/ReiNand.git
git clone --recursive https://github.com/delebile/arm9loaderhax.git
git clone --recursive https://github.com/44670/BootNTR.git
git clone --recursive https://github.com/Cpasjuste/CtrBootManager.git

# Patch and build the homebrew

# Brahma2
cd $dir_build/Brahma2;
echo "Building Brahma2...";
sleep 5s;
make clean;
cd $dir_build/Brahma2/include;
sed -i -e 's|/brahma/|/3ds/Brahma2/payloads/|g' $dir_build/Brahma2/include/menus.h;
cd $dir_build/Brahma2;
make;
mkdir -vp $dir_build/Brahma2/Brahma2/payloads;
mv -v $dir_build/Brahma2/Brahma2.3dsx $dir_build/Brahma2/Brahma2/;
mv -v $dir_build/Brahma2/Brahma2.smdh $dir_build/Brahma2/Brahma2/;
mv -v $dir_build/Brahma2/Brahma2 $dir_3ds/;
echo "Done!";

# uncart
cd $dir_build/uncart;
echo "Building Uncart...";
sleep 5s;
make clean;
make;
mv -v $dir_build/uncart/uncart.bin $dir_3ds/Brahma2/payloads/Uncart.bin;
echo "Done!";

# EmuNAND9
cd $dir_build/EmuNAND9;
echo "Building EmuNAND9...";
sleep 5s;
make clean;
make;
mv -v $dir_build/EmuNAND9/output/EmuNAND9.bin $dir_3ds/Brahma2/payloads/EmuNAND9.bin;
echo "Done!";

# Decrypt9WIP
cd $dir_build/Decrypt9WIP;
echo "Building Decrypt9WIP...";
sleep 5s;
make clean;
make;
mv -v $dir_build/Decrypt9WIP/output/Decrypt9WIP.bin $dir_3ds/Brahma2/payloads/Decrypt9WIP.bin;
echo "Done!";

# MiniPasta
cd $dir_build/MiniPasta;
echo "Building MiniPasta...";
sleep 5s;
make clean;
make;
mkdir $dir_build/MiniPasta/MiniPasta;
mv -v $dir_build/MiniPasta/MiniPasta.3dsx $dir_build/MiniPasta/MiniPasta/;
mv -v $dir_build/MiniPasta/MiniPasta.smdh $dir_build/MiniPasta/MiniPasta/;
mv -v $dir_build/MiniPasta/MiniPasta $dir_3ds/;
echo "Done!";

# CakesFW
cd $dir_build/CakesForeveryWan;
echo "Building CakesForeveryWan...";
sleep 5s;
make clean;
cd $dir_build/CakesForeveryWan/source;
sed -i -e 's|"/cakes"|"/3ds/Cakes/cakes"|g' $dir_build/CakesForeveryWan/source/paths.h;
sed -i -e 's|#define PATH_SLOT0X25KEYX "/slot0x25keyX.bin"|#define PATH_SLOT0X25KEYX PATH_CAKES "/slot0x25keyX.bin"|g' $dir_build/CakesForeveryWan/source/paths.h;
sed -i -e 's|#define PATH_SLOT0X11KEY96 "/slot0x11key96.bin"|#define PATH_SLOT0X11KEY96 PATH_CAKES "/slot0x11key96.bin"|g' $dir_build/CakesForeveryWan/source/paths.h;
cd $dir_build/CakesForeveryWan/CakeBrah/;
sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes/cakes/|g' $dir_build/CakesForeveryWan/CakeBrah/Makefile;
cd $dir_build/CakesForeveryWan/CakeHax/;
sed -i -e 's|filepath ?=|filepath ?= 3ds/Cakes/cakes/|g' $dir_build/CakesForeveryWan/CakeHax/Makefile;
cd $dir_build/CakesForeveryWan/;
make;
mv -v $dir_build/CakesForeveryWan/out/Cakes.dat $dir_build/CakesForeveryWan/out/cakes/;
cp -v $dir_build/CakesForeveryWan/build/main.bin $dir_build/CakesForeveryWan/out/cakes/arm9loaderhax.bin;
mv -v $dir_build/CakesForeveryWan/out/cakes $dir_build/CakesForeveryWan/out/3ds/Cakes/;
cp -v $dep/slot* $dir_build/CakesForeveryWan/out/3ds/Cakes/cakes/;
cp -rRv $dir_build/CakesForeveryWan/out/3ds/Cakes $dir_3ds/Cakes-n3DS;
cp -rRv $dir_build/CakesForeveryWan/out/3ds/Cakes $dir_3ds/Cakes-o3DS;
cd $dir_3ds/Cakes-n3DS/cakes;
wget $n3ds_cetk;
wget $n3ds_firm;
cp -v $dep/firmkey.bin-n3ds $dir_3ds/Cakes-n3DS/cakes/firmkey.bin;
mv -v $dir_3ds/Cakes-n3DS/cakes/000000* $dir_3ds/Cakes-n3DS/cakes/firmware.bin
cd $dir_3ds/Cakes-o3DS/cakes;
wget $o3ds_cetk;
wget $o3ds_firm;
cp -v $dep/firmkey.bin-o3ds $dir_3ds/Cakes-o3DS/cakes/firmkey.bin;
mv -v $dir_3ds/Cakes-o3DS/cakes/000000* $dir_3ds/Cakes-o3DS/cakes/firmware.bin
echo "Done!"

# ReiNand
cd $dir_build/ReiNand;
echo "Building ReiNand..."
sleep 5s;
make clean;
cd $dir_build/ReiNand/source;
sed -i -e 's|"/rei/splash.bin"|"/3ds/ReiNand/rei/splash.bin"|g' $dir_build/ReiNand/source/draw.c;
sed -i -e 's|"/rei/firmware.bin"|"/3ds/ReiNand/rei/firmware.bin"|g' $dir_build/ReiNand/source/firm.c;
sed -i -e 's|"/rei/emunand/emunand.bin"|"/3ds/ReiNand/rei/emunand/emunand.bin"|g' $dir_build/ReiNand/source/firm.c;
sed -i -e 's|"/rei/thread/arm9.bin"|"/3ds/ReiNand/rei/thread/arm9.bin"|g' $dir_build/ReiNand/source/firm.c;
cd $dir_build/ReiNand/CakeBrah;
sed -i -e 's|filepath ?=|filepath ?= 3ds/ReiNand/rei/|g' $dir_build/CakeBrah/Makefile;
cd $dir_build/ReiNand/CakeHax;
sed -i -e 's|filepath ?=|filepath ?= 3ds/ReiNand/rei/|g' $dir_build/CakeHax/Makefile;
cd $dir_build/ReiNand/;
make;
make a9lh;
mv -v $dir_build/ReiNand/out/ReiNand.dat $dir_build/ReiNand/out/rei/;
mv -v $dir_build/ReiNand/out/arm9loaderhax.bin $dir_build/ReiNand/out/rei/;
mv -v $dir_build/ReiNand/out/rei $dir_build/ReiNand/out/3ds/ReiNand/;
mv -v $dir_build/ReiNand/out/3ds/ReiNand $dir_3ds/;
echo "Done!"

# Arm9loaderhax n3DS
echo "Building Arm9loaderhax for n3DS..."
sleep 5s;
cd $dir_build/arm9loaderhax;
make clean;
cd $dir_build/arm9loaderhax/data_input;
cp -v $dep/new3ds10.firm $dir_build/arm9loaderhax/data_input;
cp -v $dep/new3ds90.firm $dir_build/arm9loaderhax/data_input;
cp -v $dep/secret_sector.bin $dir_build/arm9loaderhax/data_input;
cp -v $dep/otp.bin-n3DS $dir_build/arm9loaderhax/data_input/otp.bin;
cd $dir_build/arm9loaderhax/;
make;
mv -v $dir_build/arm9loaderhax/data_output $dir_3ds/arm9loaderhax-n3DS;
make clean;

# Arm9loaderhax o3DS
echo "Building Arm9loaderhax for o3DS..."
sleep 5s;
cd $dir_build/arm9loaderhax;
cd $dir_build/arm9loaderhax/data_input;
rm $dir_build/arm9loaderhax/data_input/*;
make clean;
cp -v $dep/new3ds10.firm $dir_build/arm9loaderhax/data_input;
cp -v $dep/new3ds90.firm $dir_build/arm9loaderhax/data_input;
cp -v $dep/secret_sector.bin $dir_build/arm9loaderhax/data_input;
cp -v $dep/otp.bin-o3DS $dir_build/arm9loaderhax/data_input/otp.bin;
cd $dir_build/arm9loaderhax/;
make;
mv -v $dir_build/arm9loaderhax/data_output $dir_3ds/arm9loaderhax-o3DS;
echo "Done!"

# Build CtrBootManager for a9lh
<<COMMENT1
echo "Building CtrBootManager for a9lh"
sleep 5s;
cd $dir_build/CtrBootManager/source;
sed -i -e 's|#define CONFIG_PATH "/a9lh.cfg"|#define CONFIG_PATH "/a9lh_payloads/a9lh.cfg"|g' $dir_build/CtrBootManager/source/config.h
sed -i -e 's|"/a9lh.cfg"|"/a9lh_payloads/a9lh.cfg"|g' $dir_build/CtrBootManager/source/config_new.c
cd $dir_build/CtrBootManager;
mkdir -v build;
cd build;
cmake ../;
cp -v arm9loaderhax.bin $dir_out;
 Copy a9lh binaries to "/a9lh_payloads/"
cp -v $dep/;
cp -v $dep/;
cp -v $dep/;
echo "[general]
timeout = 3
recovery = 2
default = 0

[theme]
bgTop1 = 4a0031
bgTop2 = 6f0149
bgBottom = 6f0149
highlight = dcdcdc
borders = ffffff
font1 = ffffff
font2 = 000000
bgImgTop = /a9lh_payloads/bgTop.bin
bgImgBot = /a9lh_payloads/bgBot.bin

[entry]
title = Cakes
path =  /3ds/Cakes/cakes/arm9loaderhax.bin
offset = 0
key = -1

[entry]
title = ReiNand
path =  /3ds/ReiNand/rei/arm9loaderhax.bin
offset = 0
key = -1

[entry]
title = Decrypt9WIP
path =  /3ds/Brahma2/payloads/Decrypt9WIP.bin
offset = 0x12000
key = 3

[entry]
title = EmuNAND9
path =  /3ds/Brahma2/payloads/EmuNAND.bin
offset = 0x12000
key = 3

[entry]
title = Uncart
path =  /3ds/Brahma2/payloads/Uncart.bin
offset = 0x12000
key = 3" > $dir_a9lh/;
#echo "Done!"
COMMENT1

# Build BootNTR and extract ntr.bin
echo "Building BootNTR..."
sleep 5s;
cd $dir_build/BootNTR;
make clean;
cp -v $dep/makerom $dir_build/BootNTR/lib/ctrcommon/tools/makerom-linux;
chmod u+x $dir_build/BootNTR/lib/ctrcommon/tools/*linux;
make;
cp -v $dir_build/BootNTR/output/BootNTR.cia $dir_cia/apps/;
wget $ntr
unzip *.zip
cp -v $dir_build/BootNTR/ntr.bin $dir_out/;
cp -rRv $dep/filer $dir_out;
cp -rRv $dep/plugin $dir_out;
echo "Done!"

# Copy devtools
echo "Copying devtools..."
sleep 5s;
cd $dir_build;
cp -v $dep/*.cia $dir_cia/apps/;
echo "Done!"

# Copy boot.3dsx
echo "Copying boot.3dsx";
cp -v $dep/boot.3dsx $dir_out;
echo "Done!"

# Clean up
cd ~/src;
mv -v $dir_out sdmc_root-$(date +%m-%d-%Y);
rm -rf $dir_build;
exit 0;
