#!/bin/bash
# setup_scritps

dir_bin=~/.bin/

3dshb_url=https://raw.githubusercontent.com/3xkrazy/bash_scripts/master/3ds/3dshb
nandtool_url=https://raw.githubusercontent.com/3xkrazy/bash_scripts/master/3ds/nandtool
setaudio_url=https://raw.githubusercontent.com/3xkrazy/bash_scripts/master/system/setaudio
pmove_url=https://raw.githubusercontent.com/3xkrazy/bash_scripts/master/system/pmove

rm -v $dir_bin/3dshb
rm -v $dir_bin/nandtool
rm -v $dir_bin/setaudio
rm -v $dir_bin/pmove

cd $dir_bin;
wget $3dshb_url;
wget $nandtool_url;
wget $setaudio_url;
wget $pmove_url;

chmod -v u+x $dir_bin/3dshb;
chmod -v u+x $dir_bin/nandtool;
chmod -v u+x $dir_bin/setaudio;
chmod -v u+x $dir_bin/pmove;
